# Generated by Django 4.2.13 on 2024-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wantedlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("placeofbirth", models.CharField(max_length=20)),
                ("hair", models.CharField(max_length=20)),
                ("eyes", models.CharField(max_length=20)),
                ("height", models.CharField(max_length=20)),
                ("weight", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=20)),
                ("occupation", models.CharField(max_length=20)),
                ("nationalaity", models.CharField(max_length=20)),
                ("scarsandmarks", models.CharField(max_length=20)),
                ("caution", models.CharField(max_length=200)),
            ],
        ),
    ]
